spring.application.name=Pingling


spring.security.user.name= eazybytes
spring.security.user.password=12345

# make sures only spring security related logs are presented.
logging.level.org.springframework.security=TRACE
logging.pattern.console=${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss:SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}